-- MySQL Script generated by MySQL Workbench
-- Tue Aug  6 14:39:09 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tourism
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tourism
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tourism` ;
USE `tourism` ;

-- -----------------------------------------------------
-- Table `tourism`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tourism`.`customers` (
  `idCustomers` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) COLLATE 'utf8mb3_bin' NOT NULL,
  `LastName` VARCHAR(45) COLLATE 'utf8mb3_bin' NOT NULL,
  `Email` VARCHAR(45) COLLATE 'utf8mb3_bin' NOT NULL,
  `Phone` VARCHAR(45) COLLATE 'utf8mb3_bin' NOT NULL,
  PRIMARY KEY (`idCustomers`))
ENGINE = InnoDB
AUTO_INCREMENT = 5;


-- -----------------------------------------------------
-- Table `tourism`.`tours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tourism`.`tours` (
  `idTours` INT NOT NULL AUTO_INCREMENT,
  `TourName` VARCHAR(45) COLLATE 'utf8mb3_bin' NOT NULL,
  `Destination` VARCHAR(45) COLLATE 'utf8mb3_bin' NOT NULL,
  `Price` DECIMAL(10,2) NOT NULL,
  `Duration(days)` INT NOT NULL,
  PRIMARY KEY (`idTours`))
ENGINE = InnoDB
AUTO_INCREMENT = 5;


-- -----------------------------------------------------
-- Table `tourism`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tourism`.`orders` (
  `idOrders` INT NOT NULL AUTO_INCREMENT,
  `OrderDate` DATETIME NOT NULL,
  `idCustomer` INT NOT NULL,
  `idTours` INT NOT NULL,
  `TotalPrice` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idOrders`),
  INDEX `st_idCustomer_idx` (`idCustomer` ASC) VISIBLE,
  INDEX `st_tourID_idx` (`idTours` ASC) VISIBLE,
  CONSTRAINT `st_customerID`
    FOREIGN KEY (`idCustomer`)
    REFERENCES `tourism`.`customers` (`idCustomers`),
  CONSTRAINT `st_tourID`
    FOREIGN KEY (`idTours`)
    REFERENCES `tourism`.`tours` (`idTours`))
ENGINE = InnoDB
AUTO_INCREMENT = 14;


-- -----------------------------------------------------
-- Table `tourism`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tourism`.`services` (
  `idServices` INT NOT NULL AUTO_INCREMENT,
  `ServiceName` VARCHAR(100) CHARACTER SET 'utf8mb3' NOT NULL,
  `Description` VARCHAR(45) COLLATE 'utf8mb3_bin' NOT NULL,
  `Price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idServices`))
ENGINE = InnoDB
AUTO_INCREMENT = 4;


-- -----------------------------------------------------
-- Table `tourism`.`orderservices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tourism`.`orderservices` (
  `idOrderServices` INT NOT NULL AUTO_INCREMENT,
  `idOrders` INT NOT NULL,
  `idServices` INT NOT NULL,
  `Quanity` INT NOT NULL,
  PRIMARY KEY (`idOrderServices`),
  INDEX `st_orderID_idx` (`idOrders` ASC) VISIBLE,
  INDEX `st_serviceID_idx` (`idServices` ASC) VISIBLE,
  CONSTRAINT `st_orderID`
    FOREIGN KEY (`idOrders`)
    REFERENCES `tourism`.`orders` (`idOrders`),
  CONSTRAINT `st_serviceID`
    FOREIGN KEY (`idServices`)
    REFERENCES `tourism`.`services` (`idServices`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
